build:
  quality:
    filter:
      owner: lukas-slezevicius
      branch: main
    build-analysis:
      image: vaticle-ubuntu-21.04
      command: |
        ls
    dependency-analysis:
      image: vaticle-ubuntu-21.04
      command: |
        las
  correctness:
    build:
      image: vaticle-ubuntu-21.04
      command: |
        ls
    build-dependency:
      image: vaticle-ubuntu-21.04
      command: |
        ls
    test-unit:
      image: vaticle-ubuntu-21.04
      command: |
        ls
    test-integration:
      image: vaticle-ubuntu-21.04
      command: |
        ls
release:
  validation:
    validate-dependencies:
      image: vaticle-ubuntu-21.04
      command: ls
  deployment:
    deploy-github:
      image: vaticle-ubuntu-21.04
      command: |
        ls